import { useState } from 'react';
import { FileText, Plus, AlertTriangle, CheckCircle, Clock, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { Employee, Contract } from '../hrTypes';
import { contractTypeLabels } from '../hrTypes';
import { MiniStat, Badge } from './HrShared';

interface Props { employees: Employee[]; contracts: Contract[]; }

export default function HrContracts({ employees, contracts }: Props) {
  const [search, setSearch] = useState('');
  const [statusF, setStatusF] = useState('all');
  const [sel, setSel] = useState<Contract | null>(null);
  const [showNew, setShowNew] = useState(false);
  const active = contracts.filter(c => c.status === 'active').length;
  const expiring = contracts.filter(c => c.status === 'pending_renewal').length;
  const expired = contracts.filter(c => c.status === 'expired').length;
  const filtered = contracts.filter(c => (c.employee_name.includes(search) || c.id.includes(search)) && (statusF === 'all' || c.status === statusF));
  const sLabel: Record<string, string> = { active: 'ساري', expired: 'منتهي', pending_renewal: 'بحاجة تجديد', draft: 'مسودة' };
  const sVar = (s: string) => s === 'active' ? 'success' as const : s === 'expired' ? 'danger' as const : s === 'pending_renewal' ? 'warning' as const : 'default' as const;
  const isSigned = (c: Contract) => !!c.signed_date;

  return (<div className="space-y-4 sm:space-y-6">
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-3"><MiniStat label="عقود سارية" value={active} color="text-success" /><MiniStat label="بحاجة تجديد" value={expiring} color="text-warning" /><MiniStat label="منتهية" value={expired} color="text-destructive" /><MiniStat label="إجمالي العقود" value={contracts.length} /></div>
    {expiring > 0 && <div className="p-3 bg-warning/10 border border-warning/20 rounded-lg flex items-center gap-2"><AlertTriangle className="w-5 h-5 text-warning shrink-0" /><p className="text-sm text-warning">{expiring} عقد بحاجة تجديد — يرجى اتخاذ إجراء</p></div>}
    <div className="flex flex-col sm:flex-row gap-2"><div className="relative flex-1"><Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-chrome" /><input value={search} onChange={e => setSearch(e.target.value)} placeholder="بحث..." className="w-full pr-10 pl-4 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground placeholder:text-chrome/50 focus:border-gold/30 focus:outline-none" /></div><select value={statusF} onChange={e => setStatusF(e.target.value)} className="px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground"><option value="all">كل الحالات</option>{Object.entries(sLabel).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select><Button onClick={() => setShowNew(true)} className="bg-gold hover:bg-gold/90 text-black"><Plus className="w-4 h-4 ml-1" />عقد جديد</Button></div>
    <div className="space-y-2">{filtered.map(c => (<div key={c.id} className="glass-card p-4 rounded-xl border border-gold/10 hover:border-gold/20 cursor-pointer transition-all" onClick={() => setSel(c)}><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div className="flex items-center gap-3"><FileText className="w-8 h-8 text-gold shrink-0" /><div><p className="font-semibold text-foreground text-sm">{c.employee_name}</p><p className="text-xs text-chrome">{c.id} — {contractTypeLabels[c.type]||c.type}</p></div></div><div className="flex items-center gap-3"><Badge variant={sVar(c.status)}>{sLabel[c.status]||c.status}</Badge>{isSigned(c) ? <CheckCircle className="w-4 h-4 text-success" /> : <Clock className="w-4 h-4 text-warning" />}</div></div><div className="flex flex-wrap gap-4 mt-3 text-xs text-chrome"><span>من: {c.start_date}</span><span>إلى: {c.end_date}</span><span>الراتب: {c.salary.toLocaleString()} ر.س</span>{c.renewal_count > 0 && <span>تجديد: {c.renewal_count} مرة</span>}</div></div>))}</div>
    <Dialog open={!!sel} onOpenChange={() => setSel(null)}><DialogContent className="max-w-lg bg-background border-gold/20">{sel && (<><DialogHeader><DialogTitle>تفاصيل العقد — {sel.employee_name}</DialogTitle></DialogHeader><div className="grid grid-cols-2 gap-3">{[['رقم العقد',sel.id],['الموظف',sel.employee_name],['نوع العقد',contractTypeLabels[sel.type]||sel.type],['البداية',sel.start_date],['النهاية',sel.end_date],['الراتب',`${sel.salary.toLocaleString()} ر.س`],['الحالة',sLabel[sel.status]||sel.status],['التوقيع',isSigned(sel)?`موقّع (${sel.signed_date})`:'غير موقّع'],['القالب',sel.template],['التجديدات',String(sel.renewal_count)]].map(([l,v]) => <div key={l} className="p-3 bg-card/30 rounded-lg"><p className="text-xs text-chrome mb-1">{l}</p><p className="text-sm text-foreground font-medium">{v}</p></div>)}</div>{sel.terms.length > 0 && <div className="mt-3"><p className="text-xs text-chrome mb-2">بنود العقد:</p><ul className="space-y-1">{sel.terms.map((t,i) => <li key={i} className="text-xs text-foreground flex items-start gap-2"><span className="text-gold mt-0.5">•</span>{t}</li>)}</ul></div>}<div className="flex gap-2 mt-4">{!isSigned(sel) && <Button className="flex-1 bg-gold hover:bg-gold/90 text-black">توقيع إلكتروني</Button>}{sel.status==='pending_renewal' && <Button className="flex-1 bg-success hover:bg-success/90 text-white">تجديد</Button>}<Button variant="outline" className="flex-1">طباعة PDF</Button></div></>)}</DialogContent></Dialog>
    <Dialog open={showNew} onOpenChange={setShowNew}><DialogContent className="max-w-lg bg-background border-gold/20"><DialogHeader><DialogTitle>إنشاء عقد جديد</DialogTitle></DialogHeader><div className="space-y-3"><div><label className="text-xs text-chrome mb-1 block">الموظف</label><select className="w-full px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground"><option value="">اختر</option>{employees.map(e => <option key={e.id} value={e.id}>{e.name_ar}</option>)}</select></div><div><label className="text-xs text-chrome mb-1 block">نوع العقد</label><select className="w-full px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground">{Object.entries(contractTypeLabels).map(([k,v]) => <option key={k} value={k}>{v}</option>)}</select></div>{[['تاريخ البداية','date'],['تاريخ النهاية','date'],['الراتب','number']].map(([l,t]) => <div key={l}><label className="text-xs text-chrome mb-1 block">{l}</label><input type={t} className="w-full px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground focus:border-gold/30 focus:outline-none" /></div>)}<div className="flex gap-2 pt-2"><Button className="flex-1 bg-gold hover:bg-gold/90 text-black">إنشاء</Button><Button onClick={() => setShowNew(false)} variant="outline" className="flex-1">إلغاء</Button></div></div></DialogContent></Dialog>
  </div>);
}
