import { useState } from 'react';
import { Calendar, Plus, CheckCircle, XCircle, Search } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import type { LeaveRequest, Employee } from '../hrTypes';
import { leaveTypeLabels } from '../hrTypes';
import { MiniStat, Badge } from './HrShared';

interface Props { leaves: LeaveRequest[]; employees: Employee[]; onApprove: (id: string) => void; onReject: (id: string) => void; }

export default function HrLeaves({ leaves, employees, onApprove, onReject }: Props) {
  const [search, setSearch] = useState('');
  const [statusF, setStatusF] = useState('all');
  const [showNew, setShowNew] = useState(false);
  const pending = leaves.filter(l => l.status === 'pending').length;
  const filtered = leaves.filter(l => { const emp = employees.find(e => e.id === l.employee_id); return (!search || (emp && emp.name_ar.includes(search))) && (statusF === 'all' || l.status === statusF); });
  const sL: Record<string,string> = { pending:'معلق', approved:'موافق', rejected:'مرفوض' };
  const sV = (s: string) => s==='approved'?'success' as const:s==='rejected'?'danger' as const:'warning' as const;

  return (<div className="space-y-4 sm:space-y-6">
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-2 sm:gap-3"><MiniStat label="معلقة" value={pending} color="text-warning" /><MiniStat label="موافق عليها" value={leaves.filter(l=>l.status==='approved').length} color="text-success" /><MiniStat label="مرفوضة" value={leaves.filter(l=>l.status==='rejected').length} color="text-destructive" /><MiniStat label="الإجمالي" value={leaves.length} /></div>
    <div className="flex flex-col sm:flex-row gap-2"><div className="relative flex-1"><Search className="absolute right-3 top-1/2 -translate-y-1/2 w-4 h-4 text-chrome" /><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="بحث..." className="w-full pr-10 pl-4 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground placeholder:text-chrome/50 focus:border-gold/30 focus:outline-none" /></div><select value={statusF} onChange={e=>setStatusF(e.target.value)} className="px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground"><option value="all">كل الحالات</option>{Object.entries(sL).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select><Button onClick={()=>setShowNew(true)} className="bg-gold hover:bg-gold/90 text-black"><Plus className="w-4 h-4 ml-1" />طلب إجازة</Button></div>
    <div className="space-y-2">{filtered.map(l=>{const emp=employees.find(e=>e.id===l.employee_id);return(<div key={l.id} className="glass-card p-4 rounded-xl border border-gold/10"><div className="flex flex-col sm:flex-row sm:items-center justify-between gap-2"><div className="flex items-center gap-3"><div className="w-10 h-10 rounded-full bg-gold/20 flex items-center justify-center text-gold font-bold text-sm">{emp?.name_ar.charAt(0)||'?'}</div><div><p className="font-semibold text-foreground text-sm">{emp?.name_ar||'—'}</p><p className="text-xs text-chrome">{leaveTypeLabels[l.type]} — {l.days} يوم</p></div></div><div className="flex items-center gap-2"><Badge variant={sV(l.status)}>{sL[l.status]}</Badge>{l.status==='pending'&&<div className="flex gap-1"><button onClick={()=>onApprove(l.id)} className="p-1.5 rounded bg-success/10 text-success hover:bg-success/20"><CheckCircle className="w-4 h-4" /></button><button onClick={()=>onReject(l.id)} className="p-1.5 rounded bg-destructive/10 text-destructive hover:bg-destructive/20"><XCircle className="w-4 h-4" /></button></div>}</div></div><div className="flex flex-wrap gap-4 mt-2 text-xs text-chrome"><span>من: {l.start_date}</span><span>إلى: {l.end_date}</span>{l.reason&&<span>السبب: {l.reason}</span>}</div></div>);})}</div>
    {filtered.length===0&&<div className="text-center py-8"><Calendar className="w-12 h-12 text-chrome/30 mx-auto mb-3" /><p className="text-sm text-chrome">لا توجد طلبات</p></div>}
    <Dialog open={showNew} onOpenChange={setShowNew}><DialogContent className="max-w-lg bg-background border-gold/20"><DialogHeader><DialogTitle>طلب إجازة جديد</DialogTitle></DialogHeader><div className="space-y-3"><div><label className="text-xs text-chrome mb-1 block">الموظف</label><select className="w-full px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground"><option value="">اختر</option>{employees.map(e=><option key={e.id} value={e.id}>{e.name_ar}</option>)}</select></div><div><label className="text-xs text-chrome mb-1 block">النوع</label><select className="w-full px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground">{Object.entries(leaveTypeLabels).map(([k,v])=><option key={k} value={k}>{v}</option>)}</select></div>{[['تاريخ البداية','date'],['تاريخ النهاية','date']].map(([l,t])=><div key={l}><label className="text-xs text-chrome mb-1 block">{l}</label><input type={t} className="w-full px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground focus:border-gold/30 focus:outline-none" /></div>)}<div><label className="text-xs text-chrome mb-1 block">السبب</label><textarea className="w-full px-3 py-2 bg-card/50 border border-gold/10 rounded-lg text-sm text-foreground focus:border-gold/30 focus:outline-none" rows={3} /></div><div className="flex gap-2 pt-2"><Button className="flex-1 bg-gold hover:bg-gold/90 text-black">تقديم</Button><Button onClick={()=>setShowNew(false)} variant="outline" className="flex-1">إلغاء</Button></div></div></DialogContent></Dialog>
  </div>);
}
